source:

symbol: ^TWII

start: 2010-01-01

end: 2020-08-31

functions:
  - funcname: MA
    suffix: ''
    params: {}
  - funcname: MACD
    suffix: '10_30'
    params:
        fastperiod: 10
        slowperiod: 30
